---
version: "3"
services:
  paperless-ng:
    image: lscr.io/linuxserver/paperless-ng
    container_name: paperless-ng
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
#      - REDIS_URL= #optional
    volumes:
      - ./config:/config
      - /mnt/nfs/docs:/data
    ports:
      - 8000:8000
    restart: unless-stopped
