---
version: "3"
services:
  ombi:
    image: lscr.io/linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
#      - BASE_URL=/ombi #optional
    volumes:
      - ./config:/config
    ports:
      - 3579:3579
    restart: unless-stopped
