version: "3"

services: 
  valheim: 
    image: ghcr.io/lloesche/valheim-server
    container_name: valheim_serv01
    cap_add:
      - sys_nice
    volumes: 
      - /mnt/valheim/config:/config
      - /mnt/valheim/:/opt/valheim
    ports: 
      - "2456-2457:2456-2457/udp"
      - "9001:9001/tcp"
    env_file:
      - valheim.env
    restart: unless-stopped
